# Don't touch this setting!
configVersion: 1

server_name: ${CFG_SERV_NAME}

SETTINGS:
  #Do you want the plugin to remember a player's last PVP state when the login
  PERSISTENT_PVP_STATE: true
  #How much time a player must wait to use /pvp (if pvp is on) in seconds after running the command or being in pvp
  COOLDOWN: 120
  #True makes pvp off by default. False makes pvp on by default.
  DEFAULT_PVP_OFF: true
  #Show PVP on particle effects
  PARTICLES: false
  #SHOW PVP on red nametag
  NAMETAG: true
  # Give the timeframe in seconds of how long after a tree has been timbered for dectection of attacker
  TIMBER_TIMEFRAME: 2.5
  # Worlds to disable PvP toggling in (i.e. will always use the world's settings)
  BLOCKED_WORLDS: []
  # True means Trampling crops is not permissible if Anti-Grief plugins are enabled. False means its disabled
  ANTI_TRAMPLE_CROPS: true

#<pvpstate> goes in place of a player's current pvp state
#<argument> goes in place of a player's name or other arguement
MESSAGES:
  HELP_HEADER: "&a&lCommands:"
  HELP_GENERAL_USEAGE: "&aUse /pvp to change pvp state."
  HELP_VIEW_OTHERS: "&aUse /pvp status <player> to see another players pvp state."
  HELP_SET_OTHERS: "&aUse /pvp <player> to set another player's pvp state."
  NO_PLAYER: "&cPlayer not found"
  COMMAND_INVALID_PARAMETER: "&c<argument> isn't a valid arguement. Please use help"
  COMMAND_NO_PERMISSION: "&cYou do not have permission to set other's pvp state."
  COMMAND_TOO_MANY_PARAMETER: "&cToo many arguements."
  PVP_STATE_ENABLED: "&aYour pvp has been enabled!"
  PVP_STATE_DISABLED: "&aYour pvp has been disabled!"
  PVP_STATE_CHANGED_OTHERS: "&a<argument> had their pvp state changed to <pvpstate>"
  PVP_STATUS: "&aYour pvp is set to <pvpstate>"
  PVP_STATUS_OTHERS: "&a<argument> has their pvp <pvpstate>"
  PVP_DISABLED: "&cYou have pvp disabled!"
  PVP_DISABLED_OTHERS: "&c<argument> has pvp disabled!"
  PVP_COOLDOWN: "&cToo fast! You can turn off pvp in <argument> seconds."
  PVP_WORLD_CHANGE_DISABLED: "&aYour pvp has been disabled because the world you entered does not allow pvp."
  PVP_WORLD_CHANGE_REQUIRED: "&aYour pvp has been enabled because the world you enter requires pvp."
  PVP_WORLD_CANNOT_CHANGE_SELF: "&cYou cannot change pvp state in this world."
  PVP_WORLD_CANNOT_CHANGE_OTHERS: "&cpvp states cannot be changed in that world."
  RELOAD: "&cConfig reloaded"

FARM_SETTINGS:
  - "0x0 WOOD_HOE"
  - "0X0 STONE_HOE"
  - "3x3 IRON_HOE"
  - "0X0 GOLDEN_HOE"
  - "3x3 DIAMOND_HOE"
  - "5x5 NETHERITE_HOE"