name: WisecraftSMP
version: '${project.version}'
main: xyz.wisecraft.smp.WisecraftSMP
api-version: 1.18
depend: [Essentials, WisecraftCore, LuckPerms, PlaceholderAPI, NametagEdit]
authors: [General_Zimmer]
commands:
  wisecraft:
    usage: /wisecraft <parameter>
  wshop:
    description: Get to shop quickly
    usage: /wshop
  autoroles:
    description: Used to manually save or load data
    usage: /autoroles <save | load>
    permission: Wisecraftadv.manage
    permission-message: You don't have the wisecraftadv.manage permission node.
  pvp:
    description: used to change PvP state.
    usage: /pvp
    permission: pvptoggle.allow
    permission-message: You don't have the pvptoggle.allow permission node.
permission:
  wisecraft.manage:
    default: op
  wisecraft.donator:
    default: op
  Wisecraftadv.manage:
    default: op
  pvptoggle.allow:
    description: allows player to change pvp state
    default: true
  pvptoggle.others:
    description: allows player to see other player's pvp state
    default: op
  pvptoggle.others.set:
    description: allows player to set other players pvp state
    default: op
  pvptoggle.bypass:
    description: allows player to bypass cooldown
    default: op
  pvptoggle.reload:
    description: allows player to reload config
    default: op