name: WisecraftSMP
version: '${project.version}'
main: xyz.wisecraft.smp.WisecraftSMP
api-version: 1.18
depend: []
softdepend: [Multiverse-Core, UltimateTimber, Essentials, WisecraftCore,
             LuckPerms, PlaceholderAPI, NametagEdit, VeinMiner, GriefPrevention,
             Towny, WorldGuard, Jobs]
authors: [General_Zimmer]
