name: WisecraftSMP
version: '${project.version}'
main: xyz.wisecraft.smp.WisecraftSMP
api-version: 1.18
depend: []
softdepend: [Multiverse-Core, UltimateTimber, Essentials, WisecraftCore,
             LuckPerms, PlaceholderAPI, NametagEdit, VeinMiner, GriefPrevention,
             Towny, WorldGuard, Jobs]
authors: [General_Zimmer]
permission:
  wisecraft.manage:
    default: op
  wisecraft.donator:
    default: op
  Wisecraftadv.manage:
    default: op
  wisecraftsmp.admin:
    default: op
  pvptoggle.allow:
    description: allows player to change pvp state
    default: true
  pvptoggle.others:
    description: allows player to see other player's pvp state
    default: op
  pvptoggle.others.set:
    description: allows player to set other player's pvp state
    default: op
  pvptoggle.bypass:
    description: allows player to bypass cooldown
    default: op
  pvptoggle.reload:
    description: allows player to reload config
    default: op